import React, { useState } from 'react';
import {
  Crosshair,
  ShieldAlert,
  Target,
  Scale,
  Copy,
  Check,
  ArrowUpRight,
  ArrowDownRight,
  Info,
} from 'lucide-react';
import { EntryZone, StopLoss, TakeProfit } from '../types';

interface KeyLevelsCardProps {
  entryZone: EntryZone;
  stopLoss: StopLoss;
  takeProfit1: TakeProfit;
  takeProfit2: TakeProfit;
  takeProfit3?: TakeProfit;
  riskRewardRatio: string;
  asset: string;
  signal: string;
}

export const KeyLevelsCard: React.FC<KeyLevelsCardProps> = ({
  entryZone,
  stopLoss,
  takeProfit1,
  takeProfit2,
  takeProfit3,
  riskRewardRatio = '1:2.0',
  asset,
  signal,
}) => {
  const [copied, setCopied] = useState(false);

  const signalUpper = (signal || '').toUpperCase();
  const isWaitOrNoTrade =
    signalUpper.includes('WAIT') ||
    signalUpper.includes('NO TRADE') ||
    signalUpper.includes('INSUFFICIENT');

  const formatPrice = (val?: any) => {
    if (val === undefined || val === null) return '—';
    const num = typeof val === 'number' ? val : parseFloat(String(val).replace(/[^0-9.]/g, ''));
    if (isNaN(num) || num <= 0) return '—';
    return num >= 1000
      ? `$${num.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`
      : `$${num.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 6 })}`;
  };

  const safeEntryRec = entryZone?.recommended ?? 0;
  const safeEntryMin = entryZone?.min ?? safeEntryRec;
  const safeEntryMax = entryZone?.max ?? safeEntryRec;
  const safeSlPrice = stopLoss?.price ?? 0;
  const safeSlRisk = stopLoss?.percentageRisk ?? 0;
  const safeTp1Price = takeProfit1?.price ?? 0;
  const safeTp1Gain = takeProfit1?.percentageGain ?? 0;
  const safeTp1RR = takeProfit1?.riskRewardRatio ?? 0;
  const safeTp2Price = takeProfit2?.price ?? 0;
  const safeTp2Gain = takeProfit2?.percentageGain ?? 0;
  const safeTp2RR =
    typeof takeProfit2?.riskRewardRatio === 'number' && takeProfit2.riskRewardRatio > 0
      ? takeProfit2.riskRewardRatio
      : 0;

  const isZone =
    !isWaitOrNoTrade &&
    ((safeEntryMin > 0 && safeEntryMax > 0 && safeEntryMin < safeEntryMax) ||
      (typeof entryZone?.range === 'string' &&
        entryZone.range.includes('-') &&
        !entryZone.range.includes('0 - 0')));

  const entryDisplay = isWaitOrNoTrade
    ? '—'
    : safeEntryMin > 0 && safeEntryMax > 0 && safeEntryMin < safeEntryMax
    ? `${formatPrice(safeEntryMin)} – ${formatPrice(safeEntryMax)}`
    : entryZone?.range && entryZone.range.includes('-') && !entryZone.range.includes('0 - 0')
    ? entryZone.range
    : formatPrice(safeEntryRec);

  const slDisplay = isWaitOrNoTrade ? '—' : formatPrice(safeSlPrice);
  const tp1Display = isWaitOrNoTrade ? '—' : formatPrice(safeTp1Price);
  const tp2Display = isWaitOrNoTrade ? '—' : formatPrice(safeTp2Price);

  const handleCopySetup = () => {
    const text = `
🎯 [AI TRADE SETUP] ${asset || 'Detected Asset'}
Signal: ${signal || 'WAIT / NO TRADE'}
-----------------------------
📍 ${isZone ? 'Entry Zone' : 'Entry'}: ${entryDisplay}
🛑 Stop Loss: ${slDisplay}${safeSlRisk ? ` (-${safeSlRisk}%)` : ''}
🚀 Take Profit 1: ${tp1Display}${safeTp1Gain ? ` (+${safeTp1Gain}%)` : ''}
🚀 Take Profit 2: ${tp2Display}${safeTp2Gain ? ` (+${safeTp2Gain}%)` : ''}
${takeProfit3 && takeProfit3.price ? `🚀 Take Profit 3: ${formatPrice(takeProfit3.price)}\n` : ''}⚖️ Risk/Reward: ${riskRewardRatio}
-----------------------------
Generated by Falcon Analyze
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3" id="key-trade-levels-container">
      {/* Section Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="w-2.5 h-2.5 rounded-sm bg-cyan-400" />
          <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-200">
            Primary Execution Levels & Targets
          </h3>
        </div>
        <button
          onClick={handleCopySetup}
          className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 text-xs font-mono text-cyan-300 hover:text-white transition-all cursor-pointer shadow-sm"
          id="copy-trade-setup-btn"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span className="text-emerald-400">Setup Copied!</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Trade Setup</span>
            </>
          )}
        </button>
      </div>

      {/* Grid of Key Execution Levels */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        {/* 1. ENTRY ZONE (Cyan Card) */}
        <div className="rounded-xl border border-cyan-500/40 bg-gradient-to-b from-cyan-950/40 to-[#0B101D] p-4 relative overflow-hidden shadow-lg group hover:border-cyan-500/70 transition-all">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-cyan-300">
              <Crosshair className="w-4 h-4 text-cyan-400" />
              <span>{isZone ? 'ENTRY ZONE' : 'ENTRY'}</span>
            </div>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
              {entryZone?.type ? entryZone.type.replace('_', ' ') : 'LIMIT PULLBACK'}
            </span>
          </div>

          <div className="mb-2">
            <div className="text-xl sm:text-2xl font-black font-mono tracking-tight text-white flex items-baseline gap-1 break-words">
              {entryDisplay}
            </div>
            {isZone && safeEntryRec > 0 && (
              <div className="text-[11px] font-mono text-cyan-400/80 mt-0.5">
                Rec: {formatPrice(safeEntryRec)}
              </div>
            )}
          </div>

          <p className="text-[11px] text-slate-300 border-t border-cyan-500/20 pt-2 line-clamp-2">
            {entryZone?.note || 'Optimal execution zone based on chart structure.'}
          </p>
        </div>

        {/* 2. STOP LOSS (Vivid Crimson Card) */}
        <div className="rounded-xl border border-rose-500/40 bg-gradient-to-b from-rose-950/40 to-[#0B101D] p-4 relative overflow-hidden shadow-lg group hover:border-rose-500/70 transition-all">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-rose-300">
              <ShieldAlert className="w-4 h-4 text-rose-400" />
              <span>STOP LOSS</span>
            </div>
            {safeSlRisk > 0 && !isWaitOrNoTrade && (
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/30 font-bold">
                -{safeSlRisk}% Risk
              </span>
            )}
          </div>

          <div className="mb-2">
            <div className="text-2xl font-black font-mono tracking-tight text-rose-200 flex items-baseline gap-1">
              {slDisplay}
            </div>
            <div className="text-[11px] font-mono text-rose-400/80 mt-0.5 flex items-center gap-1">
              <ArrowDownRight className="w-3 h-3" /> Invalidation Level
            </div>
          </div>

          <p className="text-[11px] text-slate-300 border-t border-rose-500/20 pt-2 line-clamp-2">
            {stopLoss?.rationale || 'Structural invalidation level beyond recent swing.'}
          </p>
        </div>

        {/* 3. TAKE PROFIT 1 (Vivid Neon Emerald Card) */}
        <div className="rounded-xl border border-emerald-500/40 bg-gradient-to-b from-emerald-950/40 to-[#0B101D] p-4 relative overflow-hidden shadow-lg group hover:border-emerald-500/70 transition-all">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-emerald-300">
              <Target className="w-4 h-4 text-[#00F0A0]" />
              <span>TAKE PROFIT 1</span>
            </div>
            {safeTp1Gain > 0 && !isWaitOrNoTrade && (
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 font-bold">
                +{safeTp1Gain}%
              </span>
            )}
          </div>

          <div className="mb-2">
            <div className="text-2xl font-black font-mono tracking-tight text-emerald-200 flex items-baseline gap-1">
              {tp1Display}
            </div>
            <div className="text-[11px] font-mono text-emerald-400/80 mt-0.5 flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" /> {safeTp1RR > 0 ? `R:R ${safeTp1RR}R (Conservative)` : 'Primary Target'}
            </div>
          </div>

          <p className="text-[11px] text-slate-300 border-t border-emerald-500/20 pt-2 line-clamp-2">
            {takeProfit1?.rationale || 'Nearest realistic opposing liquidity / structural level.'}
          </p>
        </div>

        {/* 4. TAKE PROFIT 2 (Extended Target Card) */}
        <div className="rounded-xl border border-teal-500/40 bg-gradient-to-b from-teal-950/40 to-[#0B101D] p-4 relative overflow-hidden shadow-lg group hover:border-teal-500/70 transition-all">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-teal-300">
              <Target className="w-4 h-4 text-teal-400" />
              <span>TAKE PROFIT 2</span>
            </div>
            {safeTp2Gain > 0 && !isWaitOrNoTrade && (
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-teal-500/20 text-teal-300 border border-teal-500/30 font-bold">
                +{safeTp2Gain}%
              </span>
            )}
          </div>

          <div className="mb-2">
            <div className="text-2xl font-black font-mono tracking-tight text-teal-200 flex items-baseline gap-1">
              {tp2Display}
            </div>
            <div className="text-[11px] font-mono text-teal-400/80 mt-0.5 flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" /> {safeTp2RR > 0 ? `R:R ${safeTp2RR}R (Extended)` : 'Secondary Target'}
            </div>
          </div>

          <p className="text-[11px] text-slate-300 border-t border-teal-500/20 pt-2 line-clamp-2">
            {takeProfit2?.rationale || 'Extended swing objective / key structural target.'}
          </p>
        </div>
      </div>

      {/* Risk / Reward Banner */}
      <div className="bg-[#0D121F] border border-slate-800 rounded-xl p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400">
            <Scale className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs font-mono text-slate-400 uppercase tracking-wide">
              Trade Risk to Reward Ratio (R:R)
            </div>
            <div className="text-lg font-black font-mono text-amber-300">
              {riskRewardRatio}
            </div>
          </div>
        </div>

        {/* Visual Risk vs Reward Bar */}
        <div className="w-full sm:w-72">
          <div className="flex justify-between text-[10px] font-mono text-slate-400 mb-1">
            <span className="text-rose-400">Risk: 1.0</span>
            <span className="text-emerald-400">Reward: {safeTp2RR}x</span>
          </div>
          <div className="h-3 rounded-full bg-slate-800 overflow-hidden flex border border-slate-700">
            <div
              className="bg-rose-500 h-full"
              style={{ width: `${Math.max(10, Math.min(90, Math.round((1 / (1 + safeTp2RR)) * 100)))}%` }}
              title="Risk (1.0)"
            />
            <div
              className="bg-gradient-to-r from-emerald-500 to-teal-400 h-full"
              style={{ width: `${Math.max(10, Math.min(90, Math.round((safeTp2RR / (1 + safeTp2RR)) * 100)))}%` }}
              title={`Reward (${safeTp2RR}x)`}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
